services:
  web:
    build: .
    ports:
      - "8000:80"          # maps localhost:8000 → container’s port 80
    volumes:
      - ./assets:/app/assets
      - ./data:/app/data
    restart: unless-stopped